/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DimensiClient;
import ServerRMI.OperationRMI;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import ServerRMI.Services;
import java.util.HashMap;
import java.util.Map;


/**
 *
 * @author Tiago
 */
public class DimensiObjekGeometris extends javax.swing.JFrame {

    String value = "";
    OperationRMI calc;
    private double luasBaru;
    private double kelilingBaru;

    public DimensiObjekGeometris() throws RemoteException, NotBoundException, MalformedURLException {
        initComponents();
        try{
        Registry register = LocateRegistry.getRegistry("192.168.1.58");
        calc = (OperationRMI) Naming.lookup("rmi://192.168.1.58:2000/services");
        } catch (Exception e){
            e.printStackTrace();
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SisiAwal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Skala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SetelahSkala = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HitungButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LuasSetelahSkala = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        KelilingSetelahSkala = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        LuasAwal = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        KelilingAwal = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel1.setText("Menghitung Skala dan Dimensi ");

        jLabel2.setText("Sisi Awal");

        SisiAwal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SisiAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SisiAwalActionPerformed(evt);
            }
        });

        jLabel3.setText("Skala");

        Skala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkalaActionPerformed(evt);
            }
        });

        jLabel4.setText("Sisi Awal Setelah Di Skalakan");

        SetelahSkala.setBorder(null);
        SetelahSkala.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SetelahSkala.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SetelahSkalaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(SetelahSkala);

        jLabel5.setText("Luas Awal");

        jLabel6.setText("Keliling Awal");

        HitungButton.setBackground(new java.awt.Color(255, 0, 51));
        HitungButton.setForeground(new java.awt.Color(255, 255, 255));
        HitungButton.setText("Hitung");
        HitungButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HitungButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Setelah Skala");

        LuasSetelahSkala.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LuasSetelahSkalaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(LuasSetelahSkala);

        jLabel8.setText("Keliling Setelah Skala");

        KelilingSetelahSkala.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                KelilingSetelahSkalaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(KelilingSetelahSkala);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel13.setText("Objek Geometris Persegi");

        LuasAwal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LuasAwalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(LuasAwal);

        KelilingAwal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                KelilingAwalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane5.setViewportView(KelilingAwal);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("m");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel7)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Skala)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SisiAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addGap(0, 4, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(HitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel13)))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SisiAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Skala, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(HitungButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5)))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SisiAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SisiAwalActionPerformed
        // TODO add your handling code here:
         try {
        double sisiAwal = Double.parseDouble(SisiAwal.getText());
        double luasAwal = sisiAwal * sisiAwal; // Luas = sisi^2
        double kelilingAwal = 4 * sisiAwal; // Keliling = 4 * sisi

        // Menampilkan hasil ke label
        LuasAwal.setText(String.format("%.2f m²", luasAwal));
        KelilingAwal.setText(String.format("%.2f m", kelilingAwal));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk sisi awal.");
    }
        
    }//GEN-LAST:event_SisiAwalActionPerformed

    private void SkalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkalaActionPerformed

    private void SetelahSkalaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SetelahSkalaAncestorAdded
        // TODO add your handling code here:
        SetelahSkala.setEditable(false);
    }//GEN-LAST:event_SetelahSkalaAncestorAdded

    private void HitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungButtonActionPerformed
        // TODO add your handling code here:
         try {
            // Ambil input dari text field
            double sisiAwal = Double.parseDouble(SisiAwal.getText());
            double faktorSkala = Double.parseDouble(Skala.getText());

            // Hitung sisi setelah di-skala
            double sisiBaru = sisiAwal * faktorSkala;
            double luasAwal = sisiAwal * sisiAwal; // Luas = sisi^2
            double kelilingAwal = 4 * sisiAwal; // Keliling = 4 * sisi
            double luasBaru = sisiBaru * sisiBaru; // Luas setelah di-skala
            double kelilingBaru = 4 * sisiBaru; // Keliling setelah di-skala

            // Tampilkan hasil pada GUI
            SetelahSkala.setText(String.format("%.2f m", sisiBaru));
            LuasAwal.setText(String.format("%.2f m²", luasAwal));
            KelilingAwal.setText(String.format("%.2f m", kelilingAwal));
            LuasSetelahSkala.setText(String.format("%.2f m²", luasBaru));
            KelilingSetelahSkala.setText(String.format("%.2f m", kelilingBaru));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk sisi dan skala.");
        }
    }//GEN-LAST:event_HitungButtonActionPerformed

    private void LuasSetelahSkalaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LuasSetelahSkalaAncestorAdded
        // TODO add your handling code here:
         LuasSetelahSkala.setText(String.valueOf(luasBaru));
         LuasSetelahSkala.setEditable(false);
    }//GEN-LAST:event_LuasSetelahSkalaAncestorAdded

    private void KelilingSetelahSkalaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_KelilingSetelahSkalaAncestorAdded
        // TODO add your handling code here:
        KelilingSetelahSkala.setText(String.valueOf(kelilingBaru));
        KelilingSetelahSkala.setEditable(false);
    }//GEN-LAST:event_KelilingSetelahSkalaAncestorAdded

    private void LuasAwalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LuasAwalAncestorAdded
        // TODO add your handling code here:
        LuasAwal.setEditable(false);
    }//GEN-LAST:event_LuasAwalAncestorAdded

    private void KelilingAwalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_KelilingAwalAncestorAdded
        // TODO add your handling code here:
        KelilingAwal.setEditable(false);
    }//GEN-LAST:event_KelilingAwalAncestorAdded

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
        try {
            // Menjalankan aplikasi GUI
            new DimensiObjekGeometris().setVisible(true);
        } catch (RemoteException | NotBoundException | MalformedURLException e) {
            // Menangani exception yang mungkin terjadi saat inisialisasi RMI
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HitungButton;
    private javax.swing.JTextPane KelilingAwal;
    private javax.swing.JTextPane KelilingSetelahSkala;
    private javax.swing.JTextPane LuasAwal;
    private javax.swing.JTextPane LuasSetelahSkala;
    private javax.swing.JTextPane SetelahSkala;
    private javax.swing.JTextField SisiAwal;
    private javax.swing.JTextField Skala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
